// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Hu0wG2HTWVelpRlAeNtPKXSfOwg1LyU',
    appId: '1:315036667005:web:7c4d229842b40e9cb83514',
    messagingSenderId: '315036667005',
    projectId: 'todo-20cb3',
    authDomain: 'todo-20cb3.firebaseapp.com',
    storageBucket: 'todo-20cb3.appspot.com',
    measurementId: 'G-9VWJG4K5VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6LSTRgyEG7dMxsK3RJ_kn5llLtHCFzI',
    appId: '1:315036667005:android:461ed18ec1a88219b83514',
    messagingSenderId: '315036667005',
    projectId: 'todo-20cb3',
    storageBucket: 'todo-20cb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7qwQ_vaqPKNSpkLPycBlSL7cVPMAY8E',
    appId: '1:315036667005:ios:f0067dd215364edbb83514',
    messagingSenderId: '315036667005',
    projectId: 'todo-20cb3',
    storageBucket: 'todo-20cb3.appspot.com',
    iosClientId:
        '315036667005-b6li3vi0mnnubbvqvtjug7sbkoeu1rba.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX7qwQ_vaqPKNSpkLPycBlSL7cVPMAY8E',
    appId: '1:315036667005:ios:f0067dd215364edbb83514',
    messagingSenderId: '315036667005',
    projectId: 'todo-20cb3',
    storageBucket: 'todo-20cb3.appspot.com',
    iosClientId:
        '315036667005-b6li3vi0mnnubbvqvtjug7sbkoeu1rba.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
